# Generated by Django 2.0.5 on 2020-07-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_cat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fk_id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Departamento')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(max_length=150)),
                ('fk_id_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pre', models.CharField(max_length=200)),
                ('fk_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Categoria')),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fk_id_encuesta', models.ManyToManyField(to='encuesta.Encuesta')),
                ('fk_id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Pregunta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Municipio'),
        ),
    ]
